-- Run as application user VIEW_DEMO (schema = VIEW_DEMO).
-- Quoted lowercase column names match SQL generated by weaver-view (e.g. "dep_key"); unquoted Oracle names fold to uppercase and break those queries.

DROP TABLE sys_user CASCADE CONSTRAINTS;
DROP TABLE position CASCADE CONSTRAINTS;
DROP TABLE department CASCADE CONSTRAINTS;
DROP TABLE sys_dict_data CASCADE CONSTRAINTS;
DROP TABLE test_field CASCADE CONSTRAINTS;

CREATE TABLE test_field
(
    id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_id              NUMBER(19)      NULL,
    user_id              NUMBER(19)      NULL,
    status               VARCHAR2(100)   DEFAULT '0',
    del_flag             NUMBER(10)      DEFAULT 0,
    create_time          TIMESTAMP       NULL,
    create_by            VARCHAR2(64)    NULL,
    update_time          TIMESTAMP       NULL,
    update_by            VARCHAR2(64)    NULL,
    remark               VARCHAR2(500)   NULL
);

CREATE TABLE sys_dict_data
(
    dict_code   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_sort   NUMBER(10)     DEFAULT 0,
    dict_label  VARCHAR2(100)  DEFAULT '',
    dict_value  VARCHAR2(100)  DEFAULT '',
    dict_type   VARCHAR2(100)  DEFAULT '',
    css_class   VARCHAR2(100)  NULL,
    list_class  VARCHAR2(100)  NULL,
    is_default  CHAR(1)        DEFAULT 'N',
    status      CHAR(1)        DEFAULT '0',
    create_by   VARCHAR2(64)   DEFAULT '',
    create_time TIMESTAMP      NULL,
    update_by   VARCHAR2(64)   DEFAULT '',
    update_time TIMESTAMP      NULL,
    remark      VARCHAR2(500)  NULL
);

CREATE TABLE department
(
    domain_key   VARCHAR2(100) NOT NULL,
    dep_key      VARCHAR2(100) NOT NULL,
    dep_name     VARCHAR2(100) NOT NULL,
    member_count NUMBER(10)    NULL,
    stopped      NUMBER(1)     NULL,
    create_time  TIMESTAMP     NOT NULL,
    create_user  VARCHAR2(100) NOT NULL,
    update_time  TIMESTAMP     NOT NULL,
    update_user  VARCHAR2(100) NOT NULL,
    PRIMARY KEY (domain_key, dep_key)
);

INSERT INTO department (domain_key, dep_key, dep_name, member_count, stopped, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep01', '行政管理部', 5, NULL, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO department (domain_key, dep_key, dep_name, member_count, stopped, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep02', '业务拓展部', 8, NULL, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO department (domain_key, dep_key, dep_name, member_count, stopped, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep03', '技术支持部', 6, 0, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO department (domain_key, dep_key, dep_name, member_count, stopped, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep04', '行政事务组', 7, 0, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO department (domain_key, dep_key, dep_name, member_count, stopped, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep05', '后勤保障组', 8, NULL, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO department (domain_key, dep_key, dep_name, member_count, stopped, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep06', '国内业务组', 2, 0, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO department (domain_key, dep_key, dep_name, member_count, stopped, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep07', '国际业务组', 2, 0, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO department (domain_key, dep_key, dep_name, member_count, stopped, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep08', '软件开发组', 5, NULL, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO department (domain_key, dep_key, dep_name, member_count, stopped, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep09', '系统维护组', 3, 0, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO department (domain_key, dep_key, dep_name, member_count, stopped, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep10', '文件管理小组', 2, 0, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO department (domain_key, dep_key, dep_name, member_count, stopped, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep11', '会议安排小组', 2, 0, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO department (domain_key, dep_key, dep_name, member_count, stopped, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep12', '东部区域小组', 2, 0, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO department (domain_key, dep_key, dep_name, member_count, stopped, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep13', '西部区域小组', 2, 0, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO department (domain_key, dep_key, dep_name, member_count, stopped, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep14', '前端开发小组', 3, 0, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO department (domain_key, dep_key, dep_name, member_count, stopped, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep15', '后端开发小组', 3, 0, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');

CREATE TABLE position
(
    domain_key   VARCHAR2(100) NOT NULL,
    dep_key      VARCHAR2(100) NOT NULL,
    pos_key      VARCHAR2(100) NOT NULL,
    pos_name     VARCHAR2(100) NULL,
    create_time  TIMESTAMP     NOT NULL,
    create_user  VARCHAR2(100) NOT NULL,
    update_time  TIMESTAMP     NOT NULL,
    update_user  VARCHAR2(100) NOT NULL,
    PRIMARY KEY (domain_key, dep_key, pos_key)
);

INSERT INTO position (domain_key, dep_key, pos_key, pos_name, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep03', 'pos1', '开发组长', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO position (domain_key, dep_key, pos_key, pos_name, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep03', 'pos2', '软件工程师', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO position (domain_key, dep_key, pos_key, pos_name, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep02', 'pos1', '后勤组长', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO position (domain_key, dep_key, pos_key, pos_name, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'dep02', 'pos2', '后勤保障员', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');

CREATE TABLE sys_user
(
    domain_key    VARCHAR2(100) NOT NULL,
    user_key      VARCHAR2(100) NOT NULL,
    parent_user   VARCHAR2(100) NULL,
    user_name     VARCHAR2(100) NOT NULL,
    position_id   VARCHAR2(100) NOT NULL,
    department_id VARCHAR2(100) NOT NULL,
    status        VARCHAR2(10)  NULL,
    photo         VARCHAR2(100) NULL,
    remark        VARCHAR2(1000) NULL,
    create_time   TIMESTAMP     NOT NULL,
    create_user   VARCHAR2(100) NOT NULL,
    update_time   TIMESTAMP     NOT NULL,
    update_user   VARCHAR2(100) NOT NULL,
    PRIMARY KEY (user_key)
);

INSERT INTO sys_user (domain_key, user_key, parent_user, user_name, department_id, position_id, status, remark, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'STF001', NULL, 'Horne', 'dep03', 'pos1', NULL, '', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO sys_user (domain_key, user_key, parent_user, user_name, department_id, position_id, status, remark, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'STF002', 'STF001', 'Sharp', 'dep03', 'pos2', 'C', '', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO sys_user (domain_key, user_key, parent_user, user_name, department_id, position_id, status, remark, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'STF003', 'STF002', 'Johnston', 'dep03', 'pos2', NULL, '', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO sys_user (domain_key, user_key, parent_user, user_name, department_id, position_id, status, remark, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'STF004', 'STF003', 'Hahn', 'dep03', 'pos2', 'C', '', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO sys_user (domain_key, user_key, parent_user, user_name, department_id, position_id, status, remark, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'STF005', 'STF001', 'Pickett', 'dep03', 'pos1', 'A', '{{label.position}}:{{ department.field.positionId.enum {"value":"pos2","depKey":"dep03"} }}({{common.status{"value":"C"}}})', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO sys_user (domain_key, user_key, parent_user, user_name, department_id, position_id, status, remark, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'STF006', 'STF005', 'Dawson', 'dep03', 'pos2', 'C', '参数化提示信息：{{message.demo{"text":"文本","number":"123"}}}', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
INSERT INTO sys_user (domain_key, user_key, parent_user, user_name, department_id, position_id, status, remark, create_time, create_user, update_time, update_user)
VALUES
('domain1', 'STF007', 'STF006', 'Hahn', 'dep03', 'pos2', 'C', '', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');
